/* date = August 14th 2024 8:39 pm */

#ifndef JD_ICON_FONT_H
#define JD_ICON_FONT_H

#define jd_FontIcon_Cancel "\xee\xa0\x80"
#define jd_FontIcon_Plus   "\xee\xa0\x81"
#define jd_FontIcon_Minus   "\xee\xa0\x82"
#define jd_FontIcon_Popup  "\xee\xa0\x83"
#define jd_FontIcon_Landscape  "\xee\xa0\x84"
#define jd_FontIcon_Left  "\xee\xa0\x85"
#define jd_FontIcon_Right  "\xee\xa0\x86"
#define jd_FontIcon_Up  "\xee\xa0\x87"
#define jd_FontIcon_Down  "\xee\xa0\x88"
#define jd_FontIcon_Down_Small  "\xee\xa0\x89"
#define jd_FontIcon_Left_Small  "\xee\xa0\x8a"
#define jd_FontIcon_Right_Small  "\xee\xa0\x8b"
#define jd_FontIcon_Up_Small "\xee\xa0\x8c"
#define jd_FontIcon_Down_Large  "\xee\xa0\x8d"
#define jd_FontIcon_Left_Large  "\xee\xa0\x8e"
#define jd_FontIcon_Right_Large  "\xee\xa0\x8f"
#define jd_FontIcon_Up_Large  "\xee\xa0\x90"
#define jd_FontIcon_RefreshCW  "\xee\xa0\x91"
#define jd_FontIcon_Play  "\xee\xa0\x92"
#define jd_FontIcon_Stop  "\xee\xa0\x93"
#define jd_FontIcon_Pause  "\xee\xa0\x94"
#define jd_FontIcon_Record  "\xee\xa0\x95"
#define jd_FontIcon_To_End  "\xee\xa0\x96"
#define jd_FontIcon_To_Start  "\xee\xa0\x97"
#define jd_FontIcon_FastForward  "\xee\xa0\x98"
#define jd_FontIcon_Rewind  "\xee\xa0\x99"
#define jd_FontIcon_Signal  "\xee\xa0\x9a"
#define jd_FontIcon_ListAdd  "\xee\xa0\x9b"
#define jd_FontIcon_ThreeDots  "\xee\xa0\x9c"
#define jd_FontIcon_Keyboard  "\xee\xa0\x9d"
#define jd_FontIcon_RefreshCCW  "\xee\xa0\x9e"
#define jd_FontIcon_Shuffle  "\xee\xa0\x9f"
#define jd_FontIcon_Loop  "\xee\xa0\xa0"
#define jd_FontIcon_Menu  "\xee\xa0\xa1"
#define jd_FontIcon_Check  "\xee\xa0\xa2"
#define jd_FontIcon_Layout  "\xee\xa0\xa3"
#define jd_FontIcon_Link  "\xee\xa0\xa4"
#define jd_FontIcon_Home  "\xee\xa0\xa5"
#define jd_FontIcon_InfoCircle  "\xee\xa0\xa6"
#define jd_FontIcon_Info  "\xee\xa0\xa7"
#define jd_FontIcon_Help  "\xee\xa0\xa8"
#define jd_FontIcon_Code  "\xee\xa0\xa9"
#define jd_FontIcon_Floppy  "\xee\xa0\xaa"
#define jd_FontIcon_History  "\xee\xa0\xab"


#endif //JD_ICON_FONT_H
